image: /thumbnail.png
title: <img src="/thumbnail.png">
baseurl: ""
url: "" 

google_analytics: G-W19Q2WFH1P

layouts_dir: "my_layouts"

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

markdown: kramdown

collections:
  category:
    output: true

include:
  - /%0a%0a%0a%0awww.linkedin.com/in/5258965548